# Generated by Django 2.1.5 on 2019-06-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=60)),
                ('handler', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('last_modify_date', models.DateField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
