# Generated by Django 2.1.5 on 2019-06-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr_site', '0002_featuresitems_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresitems',
            name='handler',
            field=models.CharField(default='Sin Asignar', max_length=60),
        ),
        migrations.AlterField(
            model_name='featuresitems',
            name='status',
            field=models.CharField(default='Proposed', max_length=60),
        ),
    ]
